services:
  server:
    build:
      context: .
      target: dev
    environment:
      NODE_ENV: development
    ports:
      - 127.0.0.1:8080:8080
      - 9229:9229
    env_file:
      - .env
    volumes:
      - .:/app
